### ISSUE TITLE
Add a StringComparison parameter in StringExtensions first 3 methods

### ISSUE THREAD

**Issue by N1K0232** [marcominerva/TinyHelpers#129]
Changes the overloads of the EqualsIgnoreCase, StartsWithIgnoreCase and EndsWithIgnoreCase by adding a StringComparison parameter set by default to OrdinalIgnoreCase. in this way the user can decide the rules to compare or check the strings

**Comment by marcominerva** [comment]
The `Equals`, `StartsWith` and `EndsWith` methods already provide overloads that accept a `StringComparison` parameter. I have created the ***IgnoreCase** methods to avoid the need to specify the comparison type. If you want to use it, you can just call the original methods.
