### ISSUE TITLE
AuthResponseOperationFilter swagger parameter

### ISSUE THREAD

**Issue by N1K0232** [marcominerva/TinyHelpers#172]
As shown in multiple live streaming, it would be useful add a AuthResponseOperationFilter object to automatically add responses for 401 and 403 status codes when the api supports authentication and authorization

**Comment by marcominerva** [comment]
As this concerns Authentication and Authorization, this Operation Filter is available in the SimpleAuthentication library: https://github.com/marcominerva/SimpleAuthentication/blob/2a3ef5e436b7b09cbe3bf5c2a932af9cc3e919b3/src/SimpleAuthentication/SwaggerExtensions.cs#L76.

**Comment by N1K0232** [comment]
Okay thank you so much for the clearance :)
