### ISSUE TITLE
Add "time-based" overloads to AsyncLock.WaitAsync

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/TinyHelpers#221]
Currently, `AsyncLock.WaitAsync` waits undefinitely for the lock. It is necessary to add overloads that take a value time and act as https://learn.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.waitasync.

**Comment by nanny07** [comment]
I am looking forward this issue and I'm wondering how to implement the same signature's methods of the `SemaphoreSlim` class.

In particular I have doubt about this one:
https://github.com/dotnet/runtime/blob/1d1bf92fcf43aa6981804dc53c5174445069c9e4/src/libraries/System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs#L563

As you can see, this can throw an Exception if the value of the `TimeSpan`, in milliseconds, is over the int.MaxValue.
Should we implement a check as well or just wait for the SempahoreSlim'class to throw the exception?

Should we write the same code multiple time (one to call the `SemaphoreSlim` method with the `int` argument, one to call the same method with a `TimeSpan`) or just implement one method (I prefer the `TimeSpan` just for readability, but it can throw)?

```csharp
/* This will never throw an Exception */
Task<AsyncLock> LockAsync(int timeoutInMilliseconds, CancellationToken cancellationToken = default)
/* This one can */
Task<AsyncLock> LockAsync(TimeSpan timeout, CancellationToken cancellationToken = default)
```

**Comment by fabriziobagala** [comment]
Hi @nanny07 and @marcominerva , I would like to propose an implementation that handles timeouts without throwing exceptions. This approach uses a result pattern that makes it easier to handle all possible outcomes (success, timeout, cancellation, invalid timeout):
https://github.com/fabriziobagala/TinyHelpers/blob/asynclock-timed-wait/src/TinyHelpers/Threading/AsyncLock.cs

**Comment by marcominerva** [comment]
Hi @fabriziobagala and thank you for your idea.

In this case, I think that exceptions are really exceptional cases. For example, the fact that a developer uses -1 as timeout value is typically the consequence of a bug in his code, so it is correct that this throws an exception.

**Comment by fabriziobagala** [comment]
@marcominerva thanks for the suggestion. I updated the branch by allowing exceptions to be thrown if the specified time intervals are incorrect.
