### ISSUE TITLE
Update net60 branch to .NET 6.0 RC1 libraries

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/TinyHelpers#50]
It it necessary to update the `net60` branch to .NET 6.0 RC1 libraries and check whether **System.Text.Json** still doesn't support the new **DateOnly** and **TimeOnly** types (and, therefore, the [DateOnlyConverter](https://github.com/marcominerva/TinyHelpers/blob/net60/src/TinyHelpers/Json/Serialization/DateOnlyConverter.cs) and [TimeOnlyConverter](https://github.com/marcominerva/TinyHelpers/blob/net60/src/TinyHelpers/Json/Serialization/TimeOnlyConverter.cs) are still needed).

**Comment by andreatosato** [comment]
Assign to @andreatosato

**Comment by marcominerva** [comment]
Closed as not necessary anymore
