### ISSUE TITLE
Using Converters in ASP.NET core and Blazor app

### ISSUE THREAD

**Issue by sandeep-eroad** [marcominerva/TinyHelpers#89]
Can you please show to use these converters in ASP.NET core and Blazor app?

**Comment by marcominerva** [comment]
Are you referring to JSON Converters?

**Comment by sandeep-eroad** [comment]
yes

**Comment by marcominerva** [comment]
You can add these converters globally, for example:

```
builder.Services.AddRazorPages().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.Converters.Add(new TimeOnlyConverter());
    options.JsonSerializerOptions.Converters.Add(new DateOnlyConverter());
});
```

Whit this code, all the properties of type `DateOnly` and `TimeOnly` will be automatically serialized and deserialized in the correct way.

Or, you can specify the converter for a specific property using the `JsonConverter `attribute:

```
public class User
{
    [JsonConverter(typeof(DateOnlyConverter))]
    public DateOnly BirthDate { get; set; }
}

```

**Comment by marcominerva** [comment]
Hi @sandeep-eroad, the provided information are enough or have you other questions?

**Comment by sandeep-eroad** [comment]
that's good, thanks.
